### ISSUE TITLE
How to use the NTRsUseLF patch?

### ISSUE THREAD

**Issue by fengyuteng** [ChrisAdderley/KerbalAtomics#60]
Hi, I  Install the NTRsUseLF patch to KSP gamedata, but it dosen't work. The fuel tank and enignes still use LH2, i want to  stop the engines and fuel tank from using LH2 and use LF instead.  Which folder should i install the cfg accuracy to? Hope to recieve your reply, thanks!

**Comment by HSJasperism** [comment]
Right now, with the version in release, you need to move the folder NTRsUseLF to directly under GameData for it to work (Kerbal Space Program\GameData\NTRsUseLF). The default folder CKAN uses will not work. There's currently a set of changes being tested for development so that folders and filenames won't matter.
